
name: Code Coverage
on:


  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: GitHub Actions Build Maven project
        run: mvn clean test install --file pom.xml

      #- name: Test
        #run: npm test

      - name: Monitor coverage
        uses: slavcodev/coverage-monitor-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coverage_path: "logs/clover.xml"
          threshold_alert: 10
          threshold_warning: 50
          threshold_metric: "lines"



#name: GitHub Actions Code Coverage

# Controls when the workflow will run
#on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  #push:
    #branches: [ "master" ]
  #pull_request:
    #branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
#jobs:
  # This workflow contains a single job called "build"
  #build:
    # The type of runner that the job will run on
    #runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    #steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- name: Checkout main branch from GitHub
        #uses: actions/checkout@v3
      

      # Runs a single command using the runners shell
     # - name: Set up JDK 1.8
     #   uses: actions/setup-java@v1
     #   with:
     #    java-version: 1.8

      # Runs a set of commands using the runners shell
      #- name: GitHub Actions Build Maven project
        #run: mvn clean test --file pom.xml
      
      #- name: Copy Coverage To Predictable Location
        #run: cp coverage/**/coverage.cobertura.xml coverage.cobertura.xml
        #run: cp $dir/*/coverage.cobertura.xml coverage.cobertura.xml
      
      #- name: Code Coverage Summary Report
        #uses: irongut/CodeCoverageSummary@v1.2.0
        #with:
          #filename: coverage.cobertura.xml
          #badge: true
          #fail_below_min: true
          #format: markdown
          #hide_branch_rate: false
          #hide_complexity: true
          #indicators: true
          #output: both
          #thresholds: '60 80'
          
      #- name: Add Coverage PR Comment
        #uses: marocchino/sticky-pull-request-comment@v2
        #if: github.event_name == 'pull_request'
        #with:
          #recreate: true
          #path: code-coverage-results.md












# This is a basic workflow to help you get started with Actions

#name: CI

# Controls when the workflow will run
#on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  #push:
    #branches: [ "master" ]
  #pull_request:
    #branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
#jobs:
  # This workflow contains a single job called "build"
  #build:
    # The type of runner that the job will run on
    #runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    #steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v3

      # Runs a single command using the runners shell
      #- name: Run a one-line script
        #run: echo Hello, world!

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
        #run: |
          #echo Add other actions to build,
          #echo test, and deploy your project.
